---
#  VIRTUALENV
- name: Install virtualenv
  pip: name=virtualenv

- name: Setup virtualenv
  pip:
    requirements: /home/{{ remote_user }}/{{ project }}/requirements.txt
    virtualenv: /home/{{ remote_user }}/.envs/{{ project }}
    #virtualenv_python: python3.7
