#  CREATE REMOTE USER
- name: Add user remote
  user: name={{ remote_user }} password={{ remote_user_password |password_hash('sha512') }} state=present shell=/bin/bash

- name: upload ssh key
  authorized_key:
    user: "{{ remote_user }}"
    key: "{{ lookup('file', '/home/{{ local_user }}/.ssh/id_rsa.pub') }}"

#  ADD KNOWN HOSTS
- name: Copy known_hosts file
  copy: src=~/.ssh/known_hosts 
        dest=/home/{{ remote_user }}/.ssh

#  SSH keys for Git Deploys
- name: Create ssh directory
  file: path=/{{ remote_user }}/.ssh state=directory

- name: Create the SSH public key file
  copy: src=~/.ssh/id_rsa.pub
        dest=/home/{{ remote_user }}/.ssh/id_rsa.pub
        mode=0644

- name: Create the SSH private key file
  copy: src=~/.ssh/id_rsa
        dest=/home/{{ remote_user }}/.ssh/id_rsa
        mode=0644