---
#  ENVIRONMENT VARIABLES
#- name: Copy environment configuration in place.
#  template:
#    src: templates/environment.j2
#    dest: "/etc/environment"
#    owner: "{{ root_user }}"
#    group: "{{ root_user }}"
#    mode: 0644

#  UPSTART - GUNICORN
- name: Copy systemd Gunicorn configuration in place.
  template:
    src: templates/systemd/systemd.gunicorn.conf.j2
    dest: "/etc/systemd/system/gunicorn.service"
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: 0755